name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - tsmock
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

        Please consider opening a ticket at [JOSM Trac](https://josm.openstreetmap.de/newticket?component=Plugin+mapillary) instead.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe the behavior you expected
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe the behavior that you saw
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the issue
      description: Please describe if and how the issue is reproducible
  - type: textarea
    id: status-report
    attributes:
      label: JOSM Status Report
      description: Please copy and paste the [Status Report](https://josm.openstreetmap.de/wiki/Help/Action/ShowStatusReport) from JOSM. This will be automatically formatted, so no need for any formatting marks.
      render: text
  - type: textarea
    attributes:
      label: Additional Information
      description: |
      Anything else that may be useful for troubleshooting and/or fixing the problem, such as error messages, screenshots, or logs.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

