#!/usr/bin/env sh
if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_PULL_REQUEST" -ne false  ] || [ "$TRAVIS_TAG" -ne false  ]; then
  bash <(curl -s https://codecov.io/bash)
  bash <(curl -s https://codecov.io/bash) -c -F model_and_api
fi
