#!/usr/bin/env bash
set -e

./gradlew build compileMinJosmVersion javadoc

echo "branch $TRAVIS_BRANCH | JDK $TRAVIS_JDK_VERSION | PR #$TRAVIS_PULL_REQUEST"

if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_JDK_VERSION" == "openjdk8" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then
  ./gradlew -Dsonar.login=$SONAR_TOKEN sonarqube
fi
